// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrC0UcrLR_w_vSaWXCw0_tXh6O3C29ag0',
    appId: '1:484483717282:web:b9cdc96095494cb221dffb',
    messagingSenderId: '484483717282',
    projectId: 'nursing-assistant-ad207',
    authDomain: 'nursing-assistant-ad207.firebaseapp.com',
    storageBucket: 'nursing-assistant-ad207.firebasestorage.app',
    measurementId: 'G-1Y7GM8FNXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhK84LA4e0D8eszhJlpFv_xfpteDBrK5I',
    appId: '1:484483717282:android:3cfbf363ca0e0ab821dffb',
    messagingSenderId: '484483717282',
    projectId: 'nursing-assistant-ad207',
    storageBucket: 'nursing-assistant-ad207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfNQIQTdPtYX-THakxZIWPfat5YP6AKww',
    appId: '1:484483717282:ios:0df21118eda478cf21dffb',
    messagingSenderId: '484483717282',
    projectId: 'nursing-assistant-ad207',
    storageBucket: 'nursing-assistant-ad207.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfNQIQTdPtYX-THakxZIWPfat5YP6AKww',
    appId: '1:484483717282:ios:0df21118eda478cf21dffb',
    messagingSenderId: '484483717282',
    projectId: 'nursing-assistant-ad207',
    storageBucket: 'nursing-assistant-ad207.firebasestorage.app',
    iosBundleId: 'com.example.iotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrC0UcrLR_w_vSaWXCw0_tXh6O3C29ag0',
    appId: '1:484483717282:web:d8f999548682f99221dffb',
    messagingSenderId: '484483717282',
    projectId: 'nursing-assistant-ad207',
    authDomain: 'nursing-assistant-ad207.firebaseapp.com',
    storageBucket: 'nursing-assistant-ad207.firebasestorage.app',
    measurementId: 'G-D1WQV4XXDY',
  );
}
